-- Document the product_requirements JSONB schema (for reference, not enforced)
COMMENT ON COLUMN orders.product_requirements IS '{
  "name": "string",
  "description": "string",
  "category": "string",
  "material": "string",
  "dimensions": "string",
  "weight": "string",
  "colors": ["string"],
  "certifications": ["string"],
  "packaging": "string",
  "quantity": "number",
  "target_unit_price_usd": "number",
  "total_budget": "string",
  "frequency": "string (unica/mensual/trimestral/etc)",
  "origin_country": "string",
  "destination_port": "string",
  "urgency": "string (alta/media/baja)",
  "reference_urls": ["string"],
  "reference_product": "string",
  "reference_brand": "string",
  "customization": "string",
  "regulations": "string",
  "samples_requested": "boolean",
  "samples_quantity": "number",
  "notes": "string"
}';
